include: package:pedantic/analysis_options.yaml

linter:
  rules:
    curly_braces_in_flow_control_structures: false # See https://github.com/dart-lang/site-www/issues/1994

analyzer:
  # If this does not work in your IDE, see https://github.com/dart-lang/sdk/issues/25551.
  # This does, however, work with `flutter analyze`.
  exclude:
    - lib/generated/** # Generated code should not be checked.
