# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/**'
      - 'client/ionic/**'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/**'
      - 'client/ionic/**'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: cd client/ionic && npm install
      - run: cd client/ionic && npm audit --audit-level=moderate
      - run: cd client/ionic && CI=true npm test
  # This builds the android APK
  build-android-debug:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '14'
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm install -g @ionic/cli
      - run: npm install
        working-directory: ./client/ionic
      - run: ionic build
        working-directory: ./client/ionic
      - run: ionic cap sync
        working-directory: ./client/ionic
      - run: ./gradlew test
        working-directory: ./client/ionic/android
      - run: ./gradlew build
        working-directory: ./client/ionic/android