# This is a basic workflow to help you get started with Actions

name: Flutter CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/**'
      - 'client/flutter/**'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/**'
      - 'client/flutter/**'

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - echo "::set-env name=FLUTTER_REVISION::$(grep revision: .metadata | sed 's/  revision: //g')"
      - uses: actions/checkout@v2
        with:
          repository: 'flutter/flutter'
          ref: $FLUTTER_REVISION
          path: '_flutter'
      - run: echo "::add-path::$GITHUB_WORKSPACE/_flutter/bin"
      - run: flutter pub get
        working-directory: ./client/flutter
      - run: flutter test
        working-directory: ./client/flutter
      - run: flutter build ios
        working-directory: ./client/flutter
        if: matrix.platform == 'macos-latest'
      - run: flutter build apk
        working-directory: ./client/flutter
