# This is a basic workflow to help you get started with Actions

name: Flutter CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/**'
      - 'client/flutter/**'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/**'
      - 'client/flutter/**'

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.12.8'
          channel: 'beta'
      - run: flutter pub get
        working-directory: ./client/flutter
      - run: flutter test
        working-directory: ./client/flutter
      - run: flutter build ios
        working-directory: ./client/flutter
        if: matrix.platform == 'macos-latest'
      - run: flutter build apk
        working-directory: ./client/flutter
