name: Flutter Format
on:
  push:
    paths:
      - '.github/workflows/**'
      - 'client/flutter/**'
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/**'
      - 'client/flutter/**'

jobs:
  test:
    name: Format on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Flutter
        run: |
          git clone https://github.com/flutter/flutter.git --depth 1 -b stable _flutter
          echo "::add-path::$GITHUB_WORKSPACE/_flutter/bin"
      - name: Check format
        run: flutter format . --set-exit-if-changed --fix
        working-directory: ./client/flutter
