name: Pull Request Labeler
on: pull_request

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v3-preview
      continue-on-error: true
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
